### ISSUE TITLE
WB not showing up when installing it from Addon manager

### ISSUE THREAD

**Issue by cheezebreeze** [KeithSloan/ImportNURBS#5]
Just installed Ubuntu 20 to help troubleshoot Linux issues. Was in a hurry and copied the FreeCAD Appimage I had, which is not the latest 19-release but fairly new.

This is not a critical problem obviously, but if it's supposed to turn up then it's something to look into.

These are the steps to reproduce:
1) In terminal:
sudo chmod +rwx FreeCAD_0.19-22846-Linux-Conda_glibc2.12-x86_64.AppImage

2) Started FreeCAD from terminal with "./Free.."

3) In FreeCAD, installed ImportNURBS from Addon Manager

4) Restarted FreeCAD

5) Checked workbench list - no ImportNURBS.

However, if I create a new document and try File -> Import, then .3dm is one of the listed formats.

OS: Ubuntu 20.04.1 LTS (ubuntu:GNOME/ubuntu)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.22846 (Git) AppImage
Build type: Release
Branch: master
Hash: 1f46b72491a0008384a6db4f2615a656249f6f08
Python version: 3.8.6
Qt version: 5.12.5
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/United States (en_US)

**Comment by KeithSloan** [comment]
I am not expecting the workbench to show up, as there is no code for a icon based workbench. There is just a '__init__.py' file that registers the importer for file type 3dm
